[package]
name = "chip8-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = "0.2.15"
rand = "0.8.5"
chip8-rs-macros = { path = "../chip8-rs-macros" }
chip8-rs-common = { path = "../chip8-rs-common" }